# Generated by Django 3.2.12 on 2022-08-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20220809_1059'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
